-- AlterTable
ALTER TABLE "IncentiveRecord" ADD COLUMN     "baseSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "incentivePercentage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSalary" DOUBLE PRECISION NOT NULL DEFAULT 0;
